"""add user session token

Revision ID: 2d26fb9efcbc
Revises: e30f714c1829
Create Date: 2026-08-09 18:54:20.554939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d26fb9efcbc'
down_revision: Union[str, Sequence[str], None] = 'e30f714c1829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('session_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_session_token'), 'users', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_session_token'), table_name='users')
    op.drop_column('users', 'session_expires_at')
    op.drop_column('users', 'session_token')
    # ### end Alembic commands ###
